### Normalize/scale distances used in EMPIRE 

"normalized BE-NL is 175 km" --> Find scaling factor and adj other distances

In [1]:
import pandas as pd 
import geopandas as gpd

In [3]:
from shapely import wkt
df_nodes = pd.read_csv("Output/nodes.csv")
df_nodes["geometry"] = df_nodes["geometry"].apply(wkt.loads)
nodes = gpd.GeoDataFrame(df_nodes, crs="EPSG:4326")
nodes = nodes.to_crs("EPSG:25833")
nodes

           Node  Longitude   Latitude                         geometry
0       Austria  14.430000  47.460000   POINT (457038.809 5256441.760)
1      Bosnia H  17.810000  44.060000   POINT (725065.181 4882376.507)
2       Belgium   4.600000  50.720000  POINT (-233330.788 5670463.302)
3      Bulgaria  25.250000  42.710000  POINT (1339724.705 4779845.144)
4   Switzerland   8.150000  46.820000   POINT (-22441.596 5207987.953)
..          ...        ...        ...                              ...
62  Nordavind A  32.012239  71.113248  POINT (1107447.567 7976118.280)
63  Nordavind D  18.808962  71.450117   POINT (635164.986 7931860.745)
64  Nordavind C  20.019911  71.728123   POINT (675483.230 7965912.714)
65  Vestavind E   3.853030  59.109692  POINT (-136458.754 6605653.720)
66    Sørvest D   3.840226  56.464644  POINT (-185922.125 6313761.564)

[67 rows x 4 columns]

In [15]:
NL = nodes[nodes["Node"] == "Netherlands"]["geometry"].reset_index()
BE = nodes[nodes["Node"] == "Belgium"]["geometry"].reset_index()
dist_NL_BE = float(NL.distance(BE)/1000) # km
dist_NL_BE

/var/folders/rd/zf3y09wj69n3q6493fx5jmtr0000gn/T/ipykernel_71651/959994079.py:3: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  dist_NL_BE = float(NL.distance(BE)/1000) # km

171.90534425748083

In [17]:
scaling_factor = 175/dist_NL_BE
scaling_factor

1.018002091534071

In [19]:
df_dist_offshore_areas = pd.read_csv("Output/dist_offshore_areas.csv")
df_dist_offshore_areas["distance"] = df_dist_offshore_areas["distance"] * scaling_factor
df_dist_offshore_areas

               Node         to_Node     distance
0       Moray Firth  Firth of Forth   215.667240
1       Moray Firth     Dogger Bank   509.370695
2    Firth of Forth     Dogger Bank   333.632410
3       Moray Firth         Hornsea   586.957998
4    Firth of Forth         Hornsea   387.595780
..              ...             ...          ...
491     Nordavind B       Sørvest D  2074.833654
492     Nordavind A       Sørvest D  2144.153844
493     Nordavind D       Sørvest D  1847.170056
494     Nordavind C       Sørvest D  1896.771101
495     Vestavind E       Sørvest D   301.383049

[496 rows x 3 columns]

In [21]:
df_offshore_to_onshore_nodes = pd.read_csv("Output/offshore_to_onshore_nodes.csv")
df_offshore_to_onshore_nodes["dist"] = df_offshore_to_onshore_nodes["dist"] * scaling_factor
df_offshore_to_onshore_nodes

,newOnshoreNode,Latitude,Longitude,fromNode,toNode,dist
0,Moray Firth-Great Brit.,58.330153,-3.185153,Moray Firth,Great Brit.,20.780646
1,Firth of Forth-Great Brit.,56.289100,-2.604618,Firth of Forth,Great Brit.,35.566804
2,Dogger Bank-Great Brit.,54.130482,-0.105043,Dogger Bank,Great Brit.,180.205598
3,Hornsea-Great Brit.,52.947018,1.205765,Hornsea,Great Brit.,107.985949
4,Outer Dowsing-Great Brit.,52.980918,0.773056,Outer Dowsing,Great Brit.,37.875607
5,Norfolk-Great Brit.,52.738909,1.679326,Norfolk,Great Brit.,33.285776
6,East Anglia-Great Brit.,52.101287,1.586886,East Anglia,Great Brit.,31.010428
7,Borssele-Belgium,51.354862,3.173056,Borssele,Belgium,67.839356
8,Borssele-Netherlands,51.704582,3.678612,Borssele,Netherlands,44.048883
9,Hollandsee Kust-Netherlands,52.294029,4.468610,Hollandsee Kust,Netherlands,36.430678
10,Helgoländer Bucht-Netherlands,53.542641,6.577499,Helgoländer Bucht,Netherlands,96.753774
11,Helgoländer Bucht-Germany,54.191807,7.865277,Helgoländer Bucht,Germany,48.342222
12,Nordsøen-Denmark,56.187073,8.124695,Nordsøen,Denmark,68.692180
13,Energyhub EU-NO2,57.984859,7.066944,Energyhub EU,NO2,341.649808
14,Energyhub EU-Great Brit.,52.848408,1.490346,Energyhub EU,Great Brit.,377.721776
15,Energyhub EU-Denmark,55.552639,8.096944,Energyhub EU,Denmark,165.276477
16,Energyhub EU-Netherlands,53.502083,6.163054,Energyhub EU,Netherlands,180.592247
17,Energyhub EU-Belgium,51.500095,4.763122,Energyhub EU,Belgium,410.612027
18,Nordvest A-NO4,66.012497,11.685416,Nordvest A,NO4,99.992955
19,Nordvest C-NO3,63.448441,7.794271,Nordvest C,NO3,69.068913
20,Vestavind A-NO3,61.847393,4.839063,Vestavind A,NO3,61.627981
21,Sønnavind A-NO2,57.960972,7.499722,Sønnavind A,NO2,50.802598
22,Sørvest C-NO2,58.424305,5.898055,Sørvest C,NO2,199.502670
23,Nordvest B-NO3,63.885941,8.524479,Nordvest B,NO3,112.479480
24,Vestavind F-NO2,59.282082,4.850277,Vestavind F,NO2,20.823649
25,Sørvest E-NO2,58.425415,5.898055,Sørvest E,NO2,129.327196
26,Sørvest A-NO2,58.535973,5.696944,Sørvest A,NO2,147.336000
27,Vestavind B-NO5,61.035934,4.508854,Vestavind B,NO5,49.312771
28,Vestavind C-NO5,60.183857,3.907812,Vestavind C,NO5,27.932525
29,Vestavind D-NO5,60.327606,4.901563,Vestavind D,NO5,29.041520
30,Sørvest F-NO2,58.071251,6.650277,Sørvest F,NO2,178.587402
31,Sørvest B-NO2,58.422359,5.891388,Sørvest B,NO2,195.251652
32,Nordavind B-NO4,71.121353,27.634895,Nordavind B,NO4,74.016040
33,Nordavind A-NO4,70.545311,30.588020,Nordavind A,NO4,82.890254
34,Nordavind D-NO4,70.280731,19.592188,Nordavind D,NO4,135.057542
35,Nordavind C-NO4,70.654686,21.944271,Nordavind C,NO4,139.913997
36,Vestavind E-NO2,59.282082,4.850277,Vestavind E,NO2,61.196428
37,Sørvest D-NO2,58.070694,6.647501,Sørvest D,NO2,250.690470

In [24]:
df_shore_to_main_transmission = pd.read_csv("Output/shore_to_main_transmission.csv")
df_shore_to_main_transmission["dist"] = df_shore_to_main_transmission["dist"] * scaling_factor
df_shore_to_main_transmission

                   newOnshoreNode       toNode        dist
0         Moray Firth-Great Brit.  Great Brit.  662.324384
1      Firth of Forth-Great Brit.  Great Brit.  425.529257
2         Dogger Bank-Great Brit.  Great Brit.  185.372814
3             Hornsea-Great Brit.  Great Brit.  174.239806
4       Outer Dowsing-Great Brit.  Great Brit.  145.683217
5             Norfolk-Great Brit.  Great Brit.  204.793424
6         East Anglia-Great Brit.  Great Brit.  210.063707
7                Borssele-Belgium      Belgium  125.578113
8            Borssele-Netherlands  Netherlands  140.194971
9     Hollandsee Kust-Netherlands  Netherlands   76.963860
10  Helgoländer Bucht-Netherlands  Netherlands  174.812209
11      Helgoländer Bucht-Germany      Germany  402.385801
12               Nordsøen-Denmark      Denmark   69.378150
13               Energyhub EU-NO2          NO2  120.839648
14       Energyhub EU-Great Brit.  Great Brit.  192.359182
15           Energyhub EU-Denmark      Denmark  100.256942
16       Energyhub EU-Netherlands  Netherlands  160.801331
17           Energyhub EU-Belgium      Belgium   89.644829
18                 Nordvest A-NO4          NO4  342.703456
19                 Nordvest C-NO3          NO3  145.700852
20                Vestavind A-NO3          NO3  330.803395
21                Sønnavind A-NO2          NO2  123.061431
22                  Sørvest C-NO2          NO2  109.374399
23                 Nordvest B-NO3          NO3  136.093720
24                Vestavind F-NO2          NO2  146.824062
25                  Sørvest E-NO2          NO2  109.292667
26                  Sørvest A-NO2          NO2  111.618347
27                Vestavind B-NO5          NO5  106.290112
28                Vestavind C-NO5          NO5  144.866106
29                Vestavind D-NO5          NO5   87.098874
30                  Sørvest F-NO2          NO2  117.062135
31                  Sørvest B-NO2          NO2  109.820867
32                Nordavind B-NO4          NO4  533.673318
33                Nordavind A-NO4          NO4  605.853405
34                Nordavind D-NO4          NO4  253.472692
35                Nordavind C-NO4          NO4  338.284720
36                Vestavind E-NO2          NO2  146.824062
37                  Sørvest D-NO2          NO2  117.177983

Export CSV

In [25]:
df_dist_offshore_areas.to_csv("Output/dist_offshore_areas_scaled.csv", index=False, encoding="utf-8-sig")
df_offshore_to_onshore_nodes.to_csv("Output/offshore_to_onshore_nodes_scaled.csv", index=False, encoding="utf-8-sig")
df_shore_to_main_transmission.to_csv("Output/shore_to_main_transmission_scaled.csv", index=False, encoding="utf-8-sig")