### Correct Vestavind B from NO5 to NO3

Originally Vestavind B assigned to NO5, but to be consistent with NVE changed to NO3

In [10]:
import pandas as pd

In [11]:
def change_to_NO5(df_row, col1, col2):
    combo = ["Vestavind B", "NO5"]
    if df_row[col1] in combo and df_row[col2] in combo:
        if df_row[col1] == "NO5":
            df_row[col1] = "NO3"
        elif df_row[col2] == "NO5":
            df_row[col2] = "NO3"
    return df_row

Directional lines

In [12]:
dl = pd.read_csv("../Output/directional_lines.csv")
col1 = "FromNode"
col2 = "ToNode"
wind_park = "Vestavind B"
dl[(dl[col1] == wind_park) | (dl[col2] == wind_park)]

        FromNode       ToNode  lineLength in km                LineType
93    Nordvest C  Vestavind B        348.352175              HVDC_Cable
94   Vestavind A  Vestavind B        105.557117              HVDC_Cable
95   Sønnavind A  Vestavind B        458.272812              HVDC_Cable
96     Sørvest C  Vestavind B        458.736657              HVDC_Cable
97    Nordvest B  Vestavind B        463.976985              HVDC_Cable
98   Vestavind F  Vestavind B        206.759443              HVDC_Cable
99     Sørvest E  Vestavind B        414.068709              HVDC_Cable
100    Sørvest A  Vestavind B        359.108406              HVDC_Cable
109  Vestavind B  Vestavind C         72.447738              HVDC_Cable
119  Vestavind B  Vestavind D         92.316090              HVDC_Cable
135  Vestavind B    Sørvest F        488.222129              HVDC_Cable
151  Vestavind B    Sørvest B        422.615580              HVDC_Cable
172  Vestavind B  Vestavind E        221.982016              HVDC_Cable
224  Vestavind B          NO5         49.312771  HVDC_OffshoreToOnshore

In [13]:
dl = dl.apply(lambda row: change_to_NO5(row, col1, col2), axis=1)
dl[(dl[col1] == wind_park) | (dl[col2] == wind_park)]

        FromNode       ToNode  lineLength in km                LineType
93    Nordvest C  Vestavind B        348.352175              HVDC_Cable
94   Vestavind A  Vestavind B        105.557117              HVDC_Cable
95   Sønnavind A  Vestavind B        458.272812              HVDC_Cable
96     Sørvest C  Vestavind B        458.736657              HVDC_Cable
97    Nordvest B  Vestavind B        463.976985              HVDC_Cable
98   Vestavind F  Vestavind B        206.759443              HVDC_Cable
99     Sørvest E  Vestavind B        414.068709              HVDC_Cable
100    Sørvest A  Vestavind B        359.108406              HVDC_Cable
109  Vestavind B  Vestavind C         72.447738              HVDC_Cable
119  Vestavind B  Vestavind D         92.316090              HVDC_Cable
135  Vestavind B    Sørvest F        488.222129              HVDC_Cable
151  Vestavind B    Sørvest B        422.615580              HVDC_Cable
172  Vestavind B  Vestavind E        221.982016              HVDC_Cable
224  Vestavind B          NO3         49.312771  HVDC_OffshoreToOnshore

In [14]:
dl.to_csv("../Output/directional_lines.csv", index=False, encoding="utf-8-sig")

Dist offshore areas

In [23]:
file = "../Output/offshore_to_onshore_nodes_scaled.csv"

In [24]:
def change_to_NO5(df_row, col1, col2):
    combo = ["Vestavind B", "NO5"]
    if df_row[col1] in combo and df_row[col2] in combo:
        if df_row[col1] == "NO5":
            df_row[col1] = "NO3"
        elif df_row[col2] == "NO5":
            df_row[col2] = "NO3"
        df_row["newOnshoreNode"] = "Vestavind B-NO3"
    return df_row

In [25]:
df = pd.read_csv(file)
col1 = "fromNode"
col2 = "toNode"
wind_park = "Vestavind B"
df[(df[col1] == wind_park) | (df[col2] == wind_park)]
df = df.apply(lambda row: change_to_NO5(row, col1, col2), axis=1)
df[(df[col1] == wind_park) | (df[col2] == wind_park)]

     newOnshoreNode   Latitude  Longitude     fromNode toNode       dist
27  Vestavind B-NO3  61.035934   4.508854  Vestavind B    NO3  49.312771

In [26]:
df.to_csv(file, index=False, encoding="utf-8-sig")

Shore to main transmission

In [31]:
file = "../Output/shore_to_main_transmission_scaled.csv"

In [32]:
def change_to_NO5(df_row, col1, col2):
    if df_row[col1] == "Vestavind B-NO5":
        df_row[col1] = "Vestavind B-NO3"
        df_row[col2] = "NO3"
    return df_row

In [33]:
df = pd.read_csv(file)
col1 = "newOnshoreNode"
col2 = "toNode"
wind_park = "Vestavind B"
df[(df[col1] == wind_park) | (df[col2] == wind_park)]
df = df.apply(lambda row: change_to_NO5(row, col1, col2), axis=1)
df

                   newOnshoreNode       toNode        dist
0         Moray Firth-Great Brit.  Great Brit.  662.324384
1      Firth of Forth-Great Brit.  Great Brit.  425.529257
2         Dogger Bank-Great Brit.  Great Brit.  185.372814
3             Hornsea-Great Brit.  Great Brit.  174.239806
4       Outer Dowsing-Great Brit.  Great Brit.  145.683217
5             Norfolk-Great Brit.  Great Brit.  204.793424
6         East Anglia-Great Brit.  Great Brit.  210.063707
7                Borssele-Belgium      Belgium  125.578113
8            Borssele-Netherlands  Netherlands  140.194971
9     Hollandsee Kust-Netherlands  Netherlands   76.963860
10  Helgoländer Bucht-Netherlands  Netherlands  174.812209
11      Helgoländer Bucht-Germany      Germany  402.385801
12               Nordsøen-Denmark      Denmark   69.378150
13               Energyhub EU-NO2          NO2  120.839648
14       Energyhub EU-Great Brit.  Great Brit.  192.359182
15           Energyhub EU-Denmark      Denmark  100.256942
16       Energyhub EU-Netherlands  Netherlands  160.801331
17           Energyhub EU-Belgium      Belgium   89.644829
18                 Nordvest A-NO4          NO4  342.703456
19                 Nordvest C-NO3          NO3  145.700852
20                Vestavind A-NO3          NO3  330.803395
21                Sønnavind A-NO2          NO2  123.061431
22                  Sørvest C-NO2          NO2  109.374399
23                 Nordvest B-NO3          NO3  136.093720
24                Vestavind F-NO2          NO2  146.824062
25                  Sørvest E-NO2          NO2  109.292667
26                  Sørvest A-NO2          NO2  111.618347
27                Vestavind B-NO3          NO3  106.290112
28                Vestavind C-NO5          NO5  144.866106
29                Vestavind D-NO5          NO5   87.098874
30                  Sørvest F-NO2          NO2  117.062135
31                  Sørvest B-NO2          NO2  109.820867
32                Nordavind B-NO4          NO4  533.673318
33                Nordavind A-NO4          NO4  605.853405
34                Nordavind D-NO4          NO4  253.472692
35                Nordavind C-NO4          NO4  338.284720
36                Vestavind E-NO2          NO2  146.824062
37                  Sørvest D-NO2          NO2  117.177983

In [34]:
df.to_csv(file, index=False, encoding="utf-8-sig")