### Wind profile data for NO areas 

Source: NVE (https://veiledere.nve.no/havvind/identifisering-av-utredningsomrader-for-havvind/metode-og-vurderinger/beregning-av-kraftproduksjon/)

To be used for scenario generation in EMPIRE

In [11]:
import pandas as pd

Useful mappings

In [29]:
AREA_CODES = dict({
    'Nordvest A': 'NVEA',
    'Nordvest C': 'NVEC',
    'Vestavind A': 'VVA',
    'Sønnavind A': 'SNVA',
    'Sydvest C': 'SRVC',
    'Nordvest B': 'NVEB',
    'Vestavind F': 'VVF',
    'Sydvest E': 'SRVE',
    'Sydvest A': 'SRVA',
    'Vestavind B': 'VVB',
    'Vestavind C': 'VVC',
    'Vestavind D': 'VVD',
    'Sydvest F': 'SRVF',
    'Sydvest B': 'SRVB',
    'Nordavind B': 'NAVB',
    'Nordavind A': 'NAVA',
    'Nordavind D': 'NAVD',
    'Nordavind C': 'NAVC',
    'Vestavind E': 'VVE',
    'Sydvest D': 'SRVD'
})

NO_AREA_TO_NORD_POOL_ZONE = dict({
    'Nordvest A': "NO4",
    'Nordvest C': "NO3",
    'Vestavind A': "NO3",
    'Sønnavind A': "NO2",
    'Sydvest C': "NO2",
    'Nordvest B': "NO3",
    'Vestavind F': "NO2",
    'Sydvest E': "NO2",
    'Sydvest A': "NO2",
    'Vestavind B': "NO3",
    'Vestavind C': "NO5",
    'Vestavind D': "NO5",
    'Sydvest F': "NO2",
    'Sydvest B': "NO2",
    'Nordavind B': "NO4",
    'Nordavind A': "NO4",
    'Nordavind D': "NO4",
    'Nordavind C': "NO4",
    'Vestavind E': "NO2",
    'Sydvest D': "NO2",
})

In [30]:
for area, code in AREA_CODES.items():
    df = pd.read_csv(f"../Data/Data_WindProfiles/{NO_AREA_TO_NORD_POOL_ZONE.get(area)}_wind_offshore_{area.replace(" ", "_")}.csv")
    df["Year"] = pd.to_datetime(df["Timestamp"]).dt.strftime('%Y').to_numpy(dtype=int)

    # Choose only data for 2015-2019 as is used in EMPIRE
    df = df[(df["Year"] > 2014) & (df["Year"] < 2020)]
    df["Timestamp"] = pd.to_datetime(df["Timestamp"]).dt.strftime('%d/%m/%Y %H:%M')

    # Rename columns for consistency (easy merge later)
    df = df.drop(columns=["Year"]).rename(columns={"Timestamp": "time", "Profile": code}).reset_index(drop=True)

    # Export shorter plug-and-play CSV
    df.to_csv(f"../Data/Data_WindProfiles_short/{NO_AREA_TO_NORD_POOL_ZONE.get(area)}_wind_offshore_{area.replace(" ", "_")}_short.csv", \
              index=False, encoding="utf-8-sig")

#### Merge together with offshore wind scenario data

In [54]:
ow_scenario_data = pd.read_csv("../Data/Data_WindProfiles_short/windoffshore.csv")

# Drop earlier NO areas
ow_scenario_data = ow_scenario_data.drop(columns=["UN", "SN1", "SN2"])

num_of_cols_before = len(ow_scenario_data.columns)
print(num_of_cols_before)

ow_scenario_data

22

,time,BE,DE,DK,FI,FR,GB,IE,NL,NO,...,FF,DB,HS,OD,NF,EA,BS,HK,HB,NS
0,01/01/2015 00:00,0.5116,0.7030,0.5928,0.5852,0.5899,0.7529,0.6691,0.5175,0.8284,...,0.97155,0.96628,0.93758,0.86616,0.86981,0.83877,0.82222,0.80266,0.89444,0.88547
1,01/01/2015 01:00,0.5036,0.6875,0.5769,0.5895,0.5705,0.7395,0.7031,0.5190,0.8531,...,0.96699,0.96952,0.94551,0.87631,0.87319,0.83901,0.81267,0.80292,0.88875,0.90264
2,01/01/2015 02:00,0.5238,0.6535,0.6154,0.5084,0.5279,0.7465,0.7375,0.5396,0.8746,...,0.95394,0.96597,0.93747,0.86807,0.88828,0.85387,0.83310,0.82459,0.86615,0.92479
3,01/01/2015 03:00,0.5404,0.6803,0.6354,0.4204,0.5033,0.7479,0.7178,0.5460,0.9074,...,0.94042,0.95541,0.92666,0.85072,0.86730,0.85469,0.84184,0.83591,0.87388,0.94740
4,01/01/2015 04:00,0.5181,0.7272,0.6622,0.3652,0.5250,0.7340,0.7119,0.5385,0.9420,...,0.94325,0.93488,0.93262,0.87742,0.85885,0.84037,0.82080,0.82446,0.90262,0.95673
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43819,31/12/2019 19:00,0.3553,0.0627,0.3277,0.6192,0.4522,0.3507,0.0428,0.0735,0.5534,...,0.54600,0.15600,0.24200,0.41600,0.50800,0.69700,0.52500,0.25800,0.12100,0.44800
43820,31/12/2019 20:00,0.3692,0.0493,0.2974,0.6115,0.4493,0.3581,0.0845,0.0794,0.6203,...,0.56700,0.25400,0.29100,0.41200,0.53000,0.70000,0.52600,0.26400,0.09500,0.38400
43821,31/12/2019 21:00,0.3326,0.0437,0.3009,0.5861,0.4829,0.3483,0.1077,0.0859,0.6819,...,0.57000,0.34400,0.33800,0.38800,0.52600,0.68200,0.49800,0.26700,0.08500,0.39200
43822,31/12/2019 22:00,0.2794,0.0495,0.3397,0.5549,0.5207,0.3278,0.0969,0.0933,0.7540,...,0.55400,0.42200,0.38600,0.38200,0.52200,0.64700,0.46700,0.27700,0.10300,0.46000
43823,31/12/2019 23:00,0.2445,0.0678,0.3788,0.5178,0.5691,0.2858,0.0626,0.1020,0.7949,...,0.55000,0.48300,0.43700,0.41000,0.52800,0.58300,0.44800,0.28900,0.14000,0.54600

In [55]:
for area, code in AREA_CODES.items():
    df = pd.read_csv(f"../Data/Data_WindProfiles_short/{NO_AREA_TO_NORD_POOL_ZONE.get(area)}_wind_offshore_{area.replace(" ", "_")}_short.csv")
    ow_scenario_data = ow_scenario_data.merge(df, on="time", how="left")
    
ow_scenario_data

,time,BE,DE,DK,FI,FR,GB,IE,NL,NO,...,VVC,VVD,SRVF,SRVB,NAVB,NAVA,NAVD,NAVC,VVE,SRVD
0,01/01/2015 00:00,0.5116,0.7030,0.5928,0.5852,0.5899,0.7529,0.6691,0.5175,0.8284,...,0.990578,0.999767,0.999769,0.999809,0.999792,0.999809,0.036156,0.108841,0.999788,0.999809
1,01/01/2015 01:00,0.5036,0.6875,0.5769,0.5895,0.5705,0.7395,0.7031,0.5190,0.8531,...,0.999766,0.999770,0.999794,0.999809,0.984819,0.999779,0.000000,0.044868,0.999799,0.999809
2,01/01/2015 02:00,0.5238,0.6535,0.6154,0.5084,0.5279,0.7465,0.7375,0.5396,0.8746,...,0.999783,0.999798,0.999809,0.999809,0.738507,0.999768,0.000000,0.001861,0.999792,0.999809
3,01/01/2015 03:00,0.5404,0.6803,0.6354,0.4204,0.5033,0.7479,0.7178,0.5460,0.9074,...,0.999781,0.999804,0.999809,0.999809,0.484476,0.966576,0.000000,0.000000,0.999804,0.999809
4,01/01/2015 04:00,0.5181,0.7272,0.6622,0.3652,0.5250,0.7340,0.7119,0.5385,0.9420,...,0.999807,0.999809,0.999809,0.999809,0.293473,0.711988,0.061455,0.000000,0.999809,0.999809
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43819,31/12/2019 19:00,0.3553,0.0627,0.3277,0.6192,0.4522,0.3507,0.0428,0.0735,0.5534,...,0.994421,0.873503,0.215321,0.247384,0.515774,0.788339,0.318274,0.000000,0.595597,0.124753
43820,31/12/2019 20:00,0.3692,0.0493,0.2974,0.6115,0.4493,0.3581,0.0845,0.0794,0.6203,...,0.999776,0.824044,0.263830,0.270437,0.444876,0.810298,0.268048,0.000749,0.595842,0.140528
43821,31/12/2019 21:00,0.3326,0.0437,0.3009,0.5861,0.4829,0.3483,0.1077,0.0859,0.6819,...,0.999768,0.863697,0.276728,0.373095,0.397604,0.766816,0.229016,0.002564,0.554006,0.203281
43822,31/12/2019 22:00,0.2794,0.0495,0.3397,0.5549,0.5207,0.3278,0.0969,0.0933,0.7540,...,0.999769,0.978837,0.267222,0.571758,0.397051,0.692031,0.213431,0.000666,0.789336,0.319079
43823,31/12/2019 23:00,0.2445,0.0678,0.3788,0.5178,0.5691,0.2858,0.0626,0.1020,0.7949,...,0.999774,0.861791,0.338976,0.829214,0.457943,0.999775,0.207185,0.004055,0.987218,0.402116

In [56]:
ow_scenario_data.columns

Index(['time', 'BE', 'DE', 'DK', 'FI', 'FR', 'GB', 'IE', 'NL', 'NO', 'SE',
       'MF', 'FF', 'DB', 'HS', 'OD', 'NF', 'EA', 'BS', 'HK', 'HB', 'NS',
       'NVEA', 'NVEC', 'VVA', 'SNVA', 'SRVC', 'NVEB', 'VVF', 'SRVE', 'SRVA',
       'VVB', 'VVC', 'VVD', 'SRVF', 'SRVB', 'NAVB', 'NAVA', 'NAVD', 'NAVC',
       'VVE', 'SRVD'],
      dtype='object')

In [57]:
num_of_cols_after = len(ow_scenario_data.columns)
print(num_of_cols_after)

print(len(AREA_CODES.keys()))

TRUE_CHECK = num_of_cols_after == num_of_cols_before + len(AREA_CODES.keys())
TRUE_CHECK

42
20

True

Export CSV

In [59]:
ow_scenario_data.to_csv("../EMPIRE_input/windoffshore.csv", index=False, encoding="utf-8-sig")